-- Sample Oracle SQL that will show conversions to other databases
CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE,
    hire_date DATE DEFAULT SYSDATE,
    salary NUMBER(10,2),
    department_id NUMBER
);

-- Insert sample data
INSERT INTO employees (name, email, hire_date, salary, department_id) 
VALUES ('John Doe', 'john.doe@company.com', SYSDATE, 50000.00, 1);

INSERT INTO employees (name, email, hire_date, salary, department_id) 
VALUES ('Jane Smith', 'jane.smith@company.com', SYSDATE, 60000.00, 2);

-- Query with Oracle-specific syntax
SELECT * FROM (
    SELECT e.*, ROWNUM rn 
    FROM employees e 
    WHERE salary > 40000 
    ORDER BY hire_date DESC
) WHERE rn <= 5;

-- Update using Oracle date function
UPDATE employees 
SET hire_date = SYSDATE 
WHERE department_id = 1;

-- Create sequence (Oracle specific)
CREATE SEQUENCE emp_seq START WITH 1 INCREMENT BY 1;

-- Use sequence in insert
INSERT INTO employees (id, name, email, salary) 
VALUES (emp_seq.NEXTVAL, 'Bob Wilson', 'bob@company.com', 55000);
